name: Test
on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - Package.*
      - Sources/**/*.swift
      - Tests/**/*.swift
      - .github/matrix.json
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  extract-matrix:
    name: Create matrix
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.extract-matrix.outputs.versions }}
      latest-macos-runner: ${{ steps.extract-matrix.outputs.latest-macos-runner }}
      latest-xcode-version: ${{ steps.extract-matrix.outputs.latest-xcode-version }}
      swift-versions: ${{ steps.extract-matrix.outputs.swift-versions }}
      platforms: ${{ steps.extract-matrix.outputs.platforms }}
    steps:
      - uses: actions/checkout@v4
      - id: extract-matrix
        run: |
          echo "versions=$(cat .github/matrix.json | jq -rc '.versions | map(.macos_runner as $macos_runner | .xcode as $xcode | .destination | map({ macos_runner: $macos_runner, xcode: $xcode, destination: . })) | flatten')" >> $GITHUB_OUTPUT
          echo "latest-macos-runner=$(cat .github/matrix.json | jq -rc '.versions | map(.macos_runner) | max')" >> $GITHUB_OUTPUT
          echo "latest-xcode-version=$(cat .github/matrix.json | jq -r '.versions | map(.xcode) | max')" >> $GITHUB_OUTPUT
          echo "swift-versions=$(cat .github/matrix.json | jq -rc '.swift_version')" >> $GITHUB_OUTPUT
  test-macos:
    name: Test
    needs: extract-matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.extract-matrix.outputs.versions) }}
      fail-fast: false
    runs-on: macos-${{ matrix.macos_runner }}
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}-${{ matrix.xcode }}-${{ matrix.destination }}
      cancel-in-progress: true
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - id: create-destination-key
        name: Create destination key for cache
        run: echo "destination-key=$(echo "xcode_${{ matrix.xcode }}-${{ matrix.destination }}" | sed -r 's/[, ]/_/g')" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: |
            .build/SourcePackages/checkouts
          key: ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ steps.create-destination-key.outputs.destination-key }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ steps.create-destination-key.outputs.destination-key }}-
      - name: Enable macro and plugin
        run: |
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: test
        run: |
          defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
          set -o pipefail && \
          xcrun xcodebuild \
            -enableCodeCoverage YES \
            -scheme "$(xcodebuild -list -json | jq -rc '.workspace.name')" \
            -destination "${{ matrix.destination }}" \
            -derivedDataPath '.build' \
            -resultBundlePath 'test_output/TestResult.xcresult' \
            clean test | xcpretty
      - name: Upload test result
        uses: actions/upload-artifact@v4
        if: ${{ matrix.xcode }} == ${{ needs.extract-matrix.outputs.latest-xcode-version }} && (success() || failure())
        with:
          name: ${{ steps.create-destination-key.outputs.destination-key }}
          path: test_output
          if-no-files-found: error
          retention-days: 1
  xcodebuild_result:
    name: Export xcodebuild test result
    needs: [extract-matrix, test-macos]
    runs-on: macOS-${{ needs.extract-matrix.outputs.latest-macos-runner }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: test_output
      - name: Merge xcresult files
        run:
          xcrun xcresulttool merge test_output/**/*.xcresult --output-path test_output/TestResults.xcresult
      - uses: slidoapp/xcresulttool@v3.1.0
        if: success() || failure()
        with:
          path: test_output/TestResults.xcresult
          show-passed-tests: false
          show-code-coverage: false
          upload-bundles: true
  test-linux:
    name: Test
    needs: extract-matrix
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}-${{ matrix.swift }}
      cancel-in-progress: true
    strategy:
      matrix:
        swift: ${{ fromJson(needs.extract-matrix.outputs.swift-versions) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-xcode-${{ matrix.swift }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-xcode-${{ matrix.swift }}-
      - name: test
        run: swift test
